// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: storage/v2/dependency_storage.proto

package storagev2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDependenciesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_time is the start of the time interval to search for the dependencies.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end_time is the end of the time interval to search for the dependencies.
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependenciesRequest) Reset() {
	*x = GetDependenciesRequest{}
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesRequest) ProtoMessage() {}

func (x *GetDependenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesRequest.ProtoReflect.Descriptor instead.
func (*GetDependenciesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v2_dependency_storage_proto_rawDescGZIP(), []int{0}
}

func (x *GetDependenciesRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetDependenciesRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

// Dependency represents a relationship between two services.
type Dependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parent is the name of the caller service.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// child is the name of the service being called.
	Child string `protobuf:"bytes,2,opt,name=child,proto3" json:"child,omitempty"`
	// call_count is the number of times the parent service called the child service.
	CallCount uint64 `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
	// source contains the origin from where the dependency was extracted.
	Source        string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_storage_v2_dependency_storage_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Dependency) GetChild() string {
	if x != nil {
		return x.Child
	}
	return ""
}

func (x *Dependency) GetCallCount() uint64 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

func (x *Dependency) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GetDependenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dependencies  []*Dependency          `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDependenciesResponse) Reset() {
	*x = GetDependenciesResponse{}
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDependenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDependenciesResponse) ProtoMessage() {}

func (x *GetDependenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v2_dependency_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDependenciesResponse.ProtoReflect.Descriptor instead.
func (*GetDependenciesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v2_dependency_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetDependenciesResponse) GetDependencies() []*Dependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_storage_v2_dependency_storage_proto protoreflect.FileDescriptor

const file_storage_v2_dependency_storage_proto_rawDesc = "" +
	"\n" +
	"#storage/v2/dependency_storage.proto\x12\x11jaeger.storage.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n" +
	"\x16GetDependenciesRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"q\n" +
	"\n" +
	"Dependency\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x14\n" +
	"\x05child\x18\x02 \x01(\tR\x05child\x12\x1d\n" +
	"\n" +
	"call_count\x18\x03 \x01(\x04R\tcallCount\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\\\n" +
	"\x17GetDependenciesResponse\x12A\n" +
	"\fdependencies\x18\x01 \x03(\v2\x1d.jaeger.storage.v2.DependencyR\fdependencies2|\n" +
	"\x10DependencyReader\x12h\n" +
	"\x0fGetDependencies\x12).jaeger.storage.v2.GetDependenciesRequest\x1a*.jaeger.storage.v2.GetDependenciesResponseBGZEgithub.com/dodopizza/jaeger-kusto/internal/proto/storage/v2;storagev2b\x06proto3"

var (
	file_storage_v2_dependency_storage_proto_rawDescOnce sync.Once
	file_storage_v2_dependency_storage_proto_rawDescData []byte
)

func file_storage_v2_dependency_storage_proto_rawDescGZIP() []byte {
	file_storage_v2_dependency_storage_proto_rawDescOnce.Do(func() {
		file_storage_v2_dependency_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v2_dependency_storage_proto_rawDesc), len(file_storage_v2_dependency_storage_proto_rawDesc)))
	})
	return file_storage_v2_dependency_storage_proto_rawDescData
}

var file_storage_v2_dependency_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_storage_v2_dependency_storage_proto_goTypes = []any{
	(*GetDependenciesRequest)(nil),  // 0: jaeger.storage.v2.GetDependenciesRequest
	(*Dependency)(nil),              // 1: jaeger.storage.v2.Dependency
	(*GetDependenciesResponse)(nil), // 2: jaeger.storage.v2.GetDependenciesResponse
	(*timestamppb.Timestamp)(nil),   // 3: google.protobuf.Timestamp
}
var file_storage_v2_dependency_storage_proto_depIdxs = []int32{
	3, // 0: jaeger.storage.v2.GetDependenciesRequest.start_time:type_name -> google.protobuf.Timestamp
	3, // 1: jaeger.storage.v2.GetDependenciesRequest.end_time:type_name -> google.protobuf.Timestamp
	1, // 2: jaeger.storage.v2.GetDependenciesResponse.dependencies:type_name -> jaeger.storage.v2.Dependency
	0, // 3: jaeger.storage.v2.DependencyReader.GetDependencies:input_type -> jaeger.storage.v2.GetDependenciesRequest
	2, // 4: jaeger.storage.v2.DependencyReader.GetDependencies:output_type -> jaeger.storage.v2.GetDependenciesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_storage_v2_dependency_storage_proto_init() }
func file_storage_v2_dependency_storage_proto_init() {
	if File_storage_v2_dependency_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v2_dependency_storage_proto_rawDesc), len(file_storage_v2_dependency_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v2_dependency_storage_proto_goTypes,
		DependencyIndexes: file_storage_v2_dependency_storage_proto_depIdxs,
		MessageInfos:      file_storage_v2_dependency_storage_proto_msgTypes,
	}.Build()
	File_storage_v2_dependency_storage_proto = out.File
	file_storage_v2_dependency_storage_proto_goTypes = nil
	file_storage_v2_dependency_storage_proto_depIdxs = nil
}
