// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: storage/v2/dependency_storage.proto

package storagev2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DependencyReader_GetDependencies_FullMethodName = "/jaeger.storage.v2.DependencyReader/GetDependencies"
)

// DependencyReaderClient is the client API for DependencyReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependencyReaderClient interface {
	// GetDependencies loads service dependencies from storage.
	GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error)
}

type dependencyReaderClient struct {
	cc grpc.ClientConnInterface
}

func NewDependencyReaderClient(cc grpc.ClientConnInterface) DependencyReaderClient {
	return &dependencyReaderClient{cc}
}

func (c *dependencyReaderClient) GetDependencies(ctx context.Context, in *GetDependenciesRequest, opts ...grpc.CallOption) (*GetDependenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDependenciesResponse)
	err := c.cc.Invoke(ctx, DependencyReader_GetDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependencyReaderServer is the server API for DependencyReader service.
// All implementations must embed UnimplementedDependencyReaderServer
// for forward compatibility.
type DependencyReaderServer interface {
	// GetDependencies loads service dependencies from storage.
	GetDependencies(context.Context, *GetDependenciesRequest) (*GetDependenciesResponse, error)
	mustEmbedUnimplementedDependencyReaderServer()
}

// UnimplementedDependencyReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDependencyReaderServer struct{}

func (UnimplementedDependencyReaderServer) GetDependencies(context.Context, *GetDependenciesRequest) (*GetDependenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedDependencyReaderServer) mustEmbedUnimplementedDependencyReaderServer() {}
func (UnimplementedDependencyReaderServer) testEmbeddedByValue()                          {}

// UnsafeDependencyReaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependencyReaderServer will
// result in compilation errors.
type UnsafeDependencyReaderServer interface {
	mustEmbedUnimplementedDependencyReaderServer()
}

func RegisterDependencyReaderServer(s grpc.ServiceRegistrar, srv DependencyReaderServer) {
	// If the following call pancis, it indicates UnimplementedDependencyReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DependencyReader_ServiceDesc, srv)
}

func _DependencyReader_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDependenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependencyReaderServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DependencyReader_GetDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependencyReaderServer).GetDependencies(ctx, req.(*GetDependenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DependencyReader_ServiceDesc is the grpc.ServiceDesc for DependencyReader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DependencyReader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jaeger.storage.v2.DependencyReader",
	HandlerType: (*DependencyReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependencies",
			Handler:    _DependencyReader_GetDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/v2/dependency_storage.proto",
}
