name: master

on:
  push:
    branches: [master]
    tags: [v*]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "**/*.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "**/*.md"

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.1

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: golangci-lint
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v .

      - name: Integration test
        run: go test -v ./test --tags=integration
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build collector
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     repository: dodopizza/jaeger-kusto-collector
      #     dockerfile: build/plugin/Dockerfile.collector
      #     tag_with_ref: true
      #     push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # - name: Build query
      #   uses: docker/build-push-action@v5
      #   with:
      #     repository: dodopizza/jaeger-kusto-query
      #     dockerfile: build/plugin/Dockerfile.query
      #     tag_with_ref: true
      #     push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # - name: Build agent
      #   uses: docker/build-push-action@v5
      #   with:
      #     repository: dodopizza/jaeger-kusto-agent
      #     dockerfile: build/plugin/Dockerfile.agent
      #     tag_with_ref: true
      #     push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # - name: Build all in one
      #   uses: docker/build-push-action@v5
      #   with:
      #     repository: dodopizza/jaeger-kusto
      #     dockerfile: build/plugin/Dockerfile
      #     tag_with_ref: true
      #     push: ${{ startsWith(github.ref, 'refs/tags/') }}

      # - name: Build plugin standalone
      #   uses: docker/build-push-action@v5
      #   with:
      #     repository: dodopizza/jaeger-kusto-plugin
      #     dockerfile: build/server/Dockerfile
      #     tag_with_ref: true
      #     push: ${{ startsWith(github.ref, 'refs/tags/') }}
